CREATE TABLE ORDERS 
(
  ORDERID NUMBER NOT NULL 
, USERID VARCHAR2(255) 
, ORDERDATE DATE 
, STARTTIME VARCHAR2(255) 
, ENDTIME VARCHAR2(255) 
, COURT CHAR 
, MARK CHAR 
, FEE NUMBER 
, CONSTRAINT ORDERS_PK PRIMARY KEY 
  (
    ORDERID 
  )
  ENABLE 
);

COMMENT ON COLUMN ORDERS.ORDERID IS '订单编号';

COMMENT ON COLUMN ORDERS.USERID IS '用户编号';

COMMENT ON COLUMN ORDERS.ORDERDATE IS '订单日期';

COMMENT ON COLUMN ORDERS.STARTTIME IS '开始时间';

COMMENT ON COLUMN ORDERS.ENDTIME IS '结束时间';

COMMENT ON COLUMN ORDERS.COURT IS '场地';

COMMENT ON COLUMN ORDERS.MARK IS '取消标志';

COMMENT ON COLUMN ORDERS.FEE IS '费用';


CREATE SEQUENCE ORDERS_SEQUENCE INCREMENT BY 1 START WITH 0 MINVALUE 0;
INSERT INTO ORDERS(ORDERID) VALUES(ORDERS_SEQUENCE.nextval);

-- --------------------------------------------------------
-- --  文件已创建 - 星期一-九月-11-2017
-- --------------------------------------------------------
-- --------------------------------------------------------
-- --  DDL for Table ORDERS
-- --------------------------------------------------------
--
--   CREATE TABLE "ORDERS"
--    (	"ORDERID" NUMBER,
-- 	"USERID" VARCHAR2(255 BYTE),
-- 	"ORDERDATE" DATE,
-- 	"STARTTIME" VARCHAR2(255 BYTE),
-- 	"ENDTIME" VARCHAR2(255 BYTE),
-- 	"COURT" CHAR(1 BYTE),
-- 	"MARK" CHAR(1 BYTE),
-- 	"FEE" NUMBER
--    ) SEGMENT CREATION IMMEDIATE
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
--  NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
--   BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "USERS" ;
--
--    COMMENT ON COLUMN "ORDERS"."ORDERID" IS '订单编号';
--    COMMENT ON COLUMN "ORDERS"."USERID" IS '用户编号';
--    COMMENT ON COLUMN "ORDERS"."ORDERDATE" IS '订单日期';
--    COMMENT ON COLUMN "ORDERS"."STARTTIME" IS '开始时间';
--    COMMENT ON COLUMN "ORDERS"."ENDTIME" IS '结束时间';
--    COMMENT ON COLUMN "ORDERS"."COURT" IS '场地';
--    COMMENT ON COLUMN "ORDERS"."MARK" IS '取消标志';
--    COMMENT ON COLUMN "ORDERS"."FEE" IS '费用';
-- REM INSERTING into ORDERS
-- SET DEFINE OFF;
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (84,'U002',to_date('11-9月 -17','DD-MON-RR'),'12:00','20:00','A',' ',460);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (85,'U003',to_date('11-9月 -17','DD-MON-RR'),'12:00','22:00','D','C',290);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (86,'U004',to_date('10-9月 -17','DD-MON-RR'),'12:00','22:00','D','C',135);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (82,'U006',to_date('11-9月 -17','DD-MON-RR'),'12:00','22:00','B',' ',580);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (83,'U001',to_date('11-9月 -17','DD-MON-RR'),'12:00','22:00','C',' ',580);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (87,'U009',to_date('09-9月 -17','DD-MON-RR'),'14:00','18:00','A',' ',200);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (88,'U010',to_date('12-9月 -17','DD-MON-RR'),'15:00','18:00','D',' ',150);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (89,'U007',to_date('11-9月 -17','DD-MON-RR'),'10:00','12:00','A',' ',60);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (90,'U003',to_date('11-9月 -17','DD-MON-RR'),'09:00','10:00','A',' ',30);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (91,'U004',to_date('09-9月 -17','DD-MON-RR'),'09:00','12:00','A',' ',120);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (92,'U002',to_date('12-9月 -17','DD-MON-RR'),'14:00','15:00','A','C',25);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (93,'U006',to_date('09-9月 -17','DD-MON-RR'),'14:00','15:00','C','C',12.5);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (103,'U004',to_date('03-8月 -17','DD-MON-RR'),'15:00','16:00','C',' ',50);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (101,'U002',to_date('01-8月 -17','DD-MON-RR'),'19:00','22:00','A',' ',200);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (102,'U003',to_date('02-8月 -17','DD-MON-RR'),'13:00','17:00','B',' ',200);
-- Insert into ORDERS (ORDERID,USERID,ORDERDATE,STARTTIME,ENDTIME,COURT,MARK,FEE) values (104,'U005',to_date('05-8月 -17','DD-MON-RR'),'09:00','11:00','D',' ',80);
-- --------------------------------------------------------
-- --  DDL for Index ORDERS_PK
-- --------------------------------------------------------
--
--   CREATE UNIQUE INDEX "ORDERS_PK" ON "ORDERS" ("ORDERID")
--   PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
--   BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "USERS" ;
-- --------------------------------------------------------
-- --  Constraints for Table ORDERS
-- --------------------------------------------------------
--
--   ALTER TABLE "ORDERS" MODIFY ("ORDERID" NOT NULL ENABLE);
--   ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDERID")
--   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
--   BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "USERS"  ENABLE;
